# Generated by Django 3.1.6 on 2021-05-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
