# Generated by Django 3.1.6 on 2021-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_tranfers',
            field=models.IntegerField(default=0),
        ),
    ]
