# Generated by Django 3.1.6 on 2021-05-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_total_tranfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.customer'),
        ),
    ]
