# Generated by Django 3.1.6 on 2021-05-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210513_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.customer'),
        ),
    ]
