# Generated by Django 3.1.6 on 2021-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210513_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
